# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: node CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 20.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run lint

  # unit-tests:
  #   runs-on: ubuntu-latest

  #   strategy:
  #     matrix:
  #       node-version: [20.x]
  #       # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

  #   steps:
  #     - uses: actions/checkout@v5
  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v5
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #         cache: 'npm'
  #     - run: npm ci
  #     - run: npm test

  end-to-end-tests:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v5
        - uses: actions/setup-node@v5
          with:
            node-version: lts/*
        - name: Install dependencies
          run: npm ci
        - name: Install Playwright Browsers (Chromium only)
          run: npx playwright install chromium --with-deps
        - name: Run Playwright tests (Chromium only)
          run: npx playwright test --project=chromium
          env: 
            NEXT_PUBLIC_YJS_SOCKET_SERVER: 'wss://long-river-3855.fly.dev'
        - uses: actions/upload-artifact@v5
          if: ${{ !cancelled() }}
          with:
            name: playwright-report
            path: playwright-report/
            retention-days: 10

  # Adding because sometimes next.js fails to build when a dependency gets bumped,
  # so it's best to always force a build
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20.x
          cache: 'npm'
      - run: npm install
      - run: rm next.config.js && mv next.config.js.gh_pages next.config.js
      - run: npm run build
        env:
          NEXT_PUBLIC_YJS_SOCKET_SERVER: 'wss://long-river-3855.fly.dev'
          NEXT_PUBLIC_GA_ID: 'G-B85SXM3GRK'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs:
      - lint
      - end-to-end-tests
      - build
      # - unit-tests
    if: github.ref_name == 'master'

    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20.x
          cache: 'npm'

      - run: npm install
      - run: rm next.config.js && mv next.config.js.gh_pages next.config.js
      - run: npm run build
        env:
          NEXT_PUBLIC_YJS_SOCKET_SERVER: 'wss://long-river-3855.fly.dev'
          NEXT_PUBLIC_GA_ID: 'G-B85SXM3GRK'

      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: dist/
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
